### ISSUE TITLE
The style sheets are inconsistent

### ISSUE THREAD

**Issue by llxxxll** [sql-machine-learning/sql-machine-learning.github.io#40]
https://sql-machine-learning.github.io/pysqlflow/doc/desigin/magic_design_doc.html
![图片](https://user-images.githubusercontent.com/1908992/56776363-85767d80-67fe-11e9-9915-fbec627e8e4c.png)

https://sql-machine-learning.github.io/doc_index/doc

![图片2](https://user-images.githubusercontent.com/1908992/56776367-890a0480-67fe-11e9-8e0b-2b1802ef62ba.png)

**Comment by wangkuiyi** [comment]
I confirm that the first two items "SQLFlow Client Design Doc" and "Magic Command Design Doc" are not in `/_config.yaml`. I don't know why they are there. I am not sure if it's the merge of my PR https://github.com/sql-machine-learning/sql-machine-learning.github.io/pull/39 caused this problem.

**Comment by mxz96102** [comment]
Doc should use doc layout to keep the style, edit it in _config.yaml, if need to ignore it in _config.yaml
```yaml
defaults:
  - scope:
      path: "pysqlflow"
    values:
        layout: doc
        nav_exclude: true
```
